### ISSUE TITLE
unable to find version `v1`

### ISSUE THREAD

**Issue by sachin-traice** [shundor/python-bandit-scan#1]
Showing an 

> Error: Unable to resolve action `shundor/bandit-action@v1`, unable to find version `v1`

 after  running

```
 `jobs:
  scan:
    name: Bandit Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Bandit Scanning
        uses: shundor/bandit-action@v1`
```

**Comment by angrymeir** [comment]
@sachin-traice the correct name is: `shundor/python-bandit-scan@v1.0`

**Comment by sumanth-lingappa** [comment]
@angrymeir, how can I check if my code has issues?

**Comment by reactive-firewall** [comment]
obligatory disclaimer: I'm not associated with this project.

Clarification on the cause and workaround (fix) for this:

- cause: This repository is named `python-bandit-scan` not `bandit-action` the initial release of this repository has no "v1" rather it only has "v1.0" 
- workaround ([as previously mentioned](https://github.com/shundor/python-bandit-scan/issues/1#issuecomment-1875272409) by @sachin-traice) the dot (.) zero (0) is required.

* This gives us the result: `shundor/python-bandit-scan@v1.0` for this repository (__OR__ perhaps you want the repository `python-bandit-scan` is based on called `bandit-action`, in which case you actually want [bandit-action](https://github.com/mdegis/bandit-action) by [Melih Değiş](https://github.com/mdegis/) and that would require `mdegis/bandit-action@v1.0` as documented on [bandit-action](https://github.com/mdegis/bandit-action))

@sachin-traice the corrected workflow for [this repository](https://github.com/shundor/python-bandit-scan) would be:

```yaml
jobs:
  scan:
    name: Bandit Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Caution this version is out of date

      - name: Bandit Scanning
        uses: shundor/python-bandit-scan@v1.0
```

OR for [bandit-action](https://github.com/mdegis/bandit-action) ([as documented](https://github.com/mdegis/bandit-action/blob/master/README.md)) would instead be:

```yaml
uses: mdegis/bandit-action@v1.0
with:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  path: "."
  level: high
  confidence: high
  exit_zero: true
```

Hope this helps.

---
Please note I will not be following this discussion further and can not be expected to respond. Sorry.
---
@shundor feel free to keep or remove this comment. It's your project after all.
